# Generated by Django 4.2.18 on 2025-01-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='second_signer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_text',
            field=models.TextField(),
        ),
    ]
