# Generated by Django 5.1.4 on 2025-01-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_contract_second_signer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='email_of_other_signer',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='second_signer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
