# Generated by Django 5.1.4 on 2025-01-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_contract_email_of_other_signer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='envelope_id',
            field=models.CharField(max_length=255),
        ),
    ]
