# Generated by Django 5.1.4 on 2025-01-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_alter_contract_envelope_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='name_of_other_signer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='envelope_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
