# Generated by Django 5.1.4 on 2025-01-17 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_contract_is_signed_contract_name_of_other_signer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='second_signer_email',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='second_signer_name',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='signed_at_recipient',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='signed_at_user',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='start_date',
        ),
    ]
